/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.avro;
@org.apache.avro.specific.AvroGenerated
public enum Type implements org.apache.avro.generic.GenericEnumSymbol<Type> {
  STRING, INTEGER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Type\",\"namespace\":\"com.example.avro\",\"symbols\":[\"STRING\",\"INTEGER\"],\"default\":\"STRING\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
